# version: "3.8"

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  bot:
    container_name: bot
    build: ./bot
    volumes:
      - ./bot:/app
    ports:
      - "5000:5000"
    command: python app.py

  backend:
    container_name: node
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/biblio
      - SEED_DB=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=http://localhost:3000/api
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
