# version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - CHOKIDAR_USEPOLLING=true # Required for hot-reloading in Windows
      # - NODE_ENV=development
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    
  # bot:
  #   build: ./bot
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - MONGO_URI=${MONGO_URI}
  #   networks:
  #     - app-network


networks:
  app-network:
    driver: bridge